spring.application.name=recipe

spring.datasource.url=jdbc:postgresql://localhost:5433/recipe_db
spring.datasource.username=reportworker_user
spring.datasource.password=report
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

show-sql=false
spring.jpa.show-sql=${show-sql}
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.generate_statistics=${show-sql}
logging.level.org.hibernate.stat=off
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
